window.demandSupplySc='US';window.demandSupplyCr='IL';window.demandSupplySr=41;window.houseAdCampaigns=["relabe"];window.demandSupplyPDI=1;window.demandSupplyDFSS=1;window.demandSupplyCRR=0.71;window.demandSupplySID='vp2xeHe3AxRba3ZDR';(function() {function x(c,a,f){if(null==c)throw new TypeError("The 'this' value for String.prototype."+f+" must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype."+f+" must not be a regular expression");return c+""}var B="function"==typeof Object.defineProperties?Object.defineProperty:function(c,a,f){if(c==Array.prototype||c==Object.prototype)return c;c[a]=f.value;return c};
function C(c){c=["object"==typeof globalThis&&globalThis,c,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var a=0;a<c.length;++a){var f=c[a];if(f&&f.Math==Math)return f}throw Error("Cannot find global object");}var E=C(this);function F(c,a){if(a){var f=E;c=c.split(".");for(var g=0;g<c.length-1;g++){var n=c[g];n in f||(f[n]={});f=f[n]}c=c[c.length-1];g=f[c];a=a(g);a!=g&&null!=a&&B(f,c,{configurable:!0,writable:!0,value:a})}}
F("String.prototype.startsWith",function(c){return c?c:function(a,f){var g=x(this,a,"startsWith");a+="";var n=g.length,q=a.length;f=Math.max(0,Math.min(f|0,g.length));for(var d=0;d<q&&f<n;)if(g[f++]!=a[d++])return!1;return d>=q}});F("Array.prototype.find",function(c){return c?c:function(a,f){a:{var g=this;g instanceof String&&(g=String(g));for(var n=g.length,q=0;q<n;q++){var d=g[q];if(a.call(f,d,q,g)){a=d;break a}}a=void 0}return a}});
F("Object.is",function(c){return c?c:function(a,f){return a===f?0!==a||1/a===1/f:a!==a&&f!==f}});F("Array.prototype.includes",function(c){return c?c:function(a,f){var g=this;g instanceof String&&(g=String(g));var n=g.length;f=f||0;for(0>f&&(f=Math.max(f+n,0));f<n;f++){var q=g[f];if(q===a||Object.is(q,a))return!0}return!1}});F("String.prototype.includes",function(c){return c?c:function(a,f){return-1!==x(this,a,"includes").indexOf(a,f||0)}});
function G(c){var a=0;return function(){return a<c.length?{done:!1,value:c[a++]}:{done:!0}}}function L(c){var a="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];return a?a.call(c):{next:G(c)}}
F("Promise",function(c){function a(d){this.f=0;this.l=void 0;this.b=[];var h=this.i();try{d(h.resolve,h.reject)}catch(l){h.reject(l)}}function f(){this.a=null}function g(d){return d instanceof a?d:new a(function(h){h(d)})}if(c)return c;f.prototype.o=function(d){if(null==this.a){this.a=[];var h=this;this.s(function(){h.L()})}this.a.push(d)};var n=E.setTimeout;f.prototype.s=function(d){n(d,0)};f.prototype.L=function(){for(;this.a&&this.a.length;){var d=this.a;this.a=[];for(var h=0;h<d.length;++h){var l=
d[h];d[h]=null;try{l()}catch(k){this.F(k)}}}this.a=null};f.prototype.F=function(d){this.s(function(){throw d;})};a.prototype.i=function(){function d(k){return function(p){l||(l=!0,k.call(h,p))}}var h=this,l=!1;return{resolve:d(this.W),reject:d(this.j)}};a.prototype.W=function(d){if(d===this)this.j(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof a)this.Y(d);else{a:switch(typeof d){case "object":var h=null!=d;break a;case "function":h=!0;break a;default:h=!1}h?this.V(d):this.v(d)}};
a.prototype.V=function(d){var h=void 0;try{h=d.then}catch(l){this.j(l);return}"function"==typeof h?this.Z(h,d):this.v(d)};a.prototype.j=function(d){this.A(2,d)};a.prototype.v=function(d){this.A(1,d)};a.prototype.A=function(d,h){if(0!=this.f)throw Error("Cannot settle("+d+", "+h+"): Promise already settled in state"+this.f);this.f=d;this.l=h;this.M()};a.prototype.M=function(){if(null!=this.b){for(var d=0;d<this.b.length;++d)q.o(this.b[d]);this.b=null}};var q=new f;a.prototype.Y=function(d){var h=this.i();
d.h(h.resolve,h.reject)};a.prototype.Z=function(d,h){var l=this.i();try{d.call(h,l.resolve,l.reject)}catch(k){l.reject(k)}};a.prototype.then=function(d,h){function l(u,t){return"function"==typeof u?function(y){try{k(u(y))}catch(A){p(A)}}:t}var k,p,z=new a(function(u,t){k=u;p=t});this.h(l(d,k),l(h,p));return z};a.prototype.catch=function(d){return this.then(void 0,d)};a.prototype.h=function(d,h){function l(){switch(k.f){case 1:d(k.l);break;case 2:h(k.l);break;default:throw Error("Unexpected state: "+
k.f);}}var k=this;null==this.b?q.o(l):this.b.push(l)};a.resolve=g;a.reject=function(d){return new a(function(h,l){l(d)})};a.race=function(d){return new a(function(h,l){for(var k=L(d),p=k.next();!p.done;p=k.next())g(p.value).h(h,l)})};a.all=function(d){var h=L(d),l=h.next();return l.done?g([]):new a(function(k,p){function z(y){return function(A){u[y]=A;t--;0==t&&k(u)}}var u=[],t=0;do u.push(void 0),t++,g(l.value).h(z(u.length-1),p),l=h.next();while(!l.done)})};return a});
F("Symbol",function(c){function a(n){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new f("jscomp_symbol_"+(n||"")+"_"+g++,n)}function f(n,q){this.B=n;B(this,"description",{configurable:!0,writable:!0,value:q})}if(c)return c;f.prototype.toString=function(){return this.B};var g=0;return a});
F("Symbol.iterator",function(c){if(c)return c;c=Symbol("Symbol.iterator");for(var a="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),f=0;f<a.length;f++){var g=E[a[f]];"function"===typeof g&&"function"!=typeof g.prototype[c]&&B(g.prototype,c,{configurable:!0,writable:!0,value:function(){return M(G(this))}})}return c});function M(c){c={next:c};c[Symbol.iterator]=function(){return this};return c}
function N(c,a){c instanceof String&&(c+="");var f=0,g={next:function(){if(f<c.length){var n=f++;return{value:a(n,c[n]),done:!1}}g.next=function(){return{done:!0,value:void 0}};return g.next()}};g[Symbol.iterator]=function(){return g};return g}F("Array.prototype.keys",function(c){return c?c:function(){return N(this,function(a){return a})}});
(function(){function c(b,e){e=void 0===e?{}:e;var m=h(b.data,b);m=b.url+(m?"?"+m:"");var r=new window.XMLHttpRequest;r.open(b.method||"GET",m,!0);b=new Promise(function(v,w){r.onreadystatechange=function(){if(4===r.readyState)return 300>r.status?v(this.responseText):e.ma?v():w(Error(this.responseText))}});r.send();return b}function a(b,e){if(k.w&&(void 0===e||e))return null;document.getElementsByTagName("head")[0].appendChild(f(b))}function f(b){var e=document.createElement("script");e.type="text/javascript";
e.src=b;e.async=!0;return e}function g(){try{return new Function("(a = 0) => a"),new Function("class A {}"),new Function("for (const a of [1]) {}"),!0}catch(b){return!1}}function n(b,e){e=void 0===e?{}:e;var m=void 0===e.host?k.c:e.host;e=void 0===e.G?window:e.G;try{var r=e.performance.getEntries().filter(function(w){return w.name.startsWith(m+b)}),v=r.find(function(w){return u.includes(w.initiatorType)});return v?{duration:Math.round(v.duration),I:q(v,r),responseEnd:Math.round(v.responseEnd)}:null}catch(w){return null}}
function q(b,e){return function(){return e.some(function(m){return!u.includes(m.initiatorType)})}()?"s":void 0===b.transferSize?"n":0===b.transferSize?"a":b.transferSize<b.encodedBodySize||0===b.encodedBodySize?"b":"c"}function d(){window.googletag=window.googletag||{};window.googletag.cmd=window.googletag.cmd||[];window.googletag.cmd.push(function(){var b=window.googletag.defineOutOfPageSlot.bind(window.googletag);window.googletag.defineOutOfPageSlot=function(e,m){var r=m===window.googletag.enums.OutOfPageFormat.INTERSTITIAL;
if(demandSupply.hsi&&demandSupply.sid&&r&&demandSupply.hsi()&&!demandSupply.sid(e))y.da();else return b(e,m)}})}function h(b,e){b=void 0===b?{}:b;return(Object.keys(b).map(function(m){return encodeURIComponent(m)+"="+encodeURIComponent(e.data[m])}).join("&")+("&dsReferer="+btoa(location.href.replace(/^https?:\/\/(www.)?/,"").replace(/\?.*$/,"").substr(0,512)))).substring(0,1E3)}function l(){return{load:function(){return!function(b,e,m,r,v,w,D){e[b]||(e[b]={},e[b].init=function(){e[b]._Q.push(["i",
arguments])},e[b].fetchBids=function(){e[b]._Q.push(["f",arguments])},e[b].setDisplayBids=function(){},e[b].targetingKeys=function(){return[]},e[b]._Q=[],w=m.createElement(r),w.async=!0,w.src=v,D=m.getElementsByTagName(r)[0],D.parentNode.insertBefore(w,D))}("apstag",window,document,"script","//c.amazon-adsystem.com/aax2/apstag.js")},$:function(){var b={};b.pubID=A.fa.T;b.adServer="googletag";b.bidTimeout=2E3;window.K&&(b.schain={oa:"1.0",complete:1,la:[{ia:"relabe.com",sid:window.K,ka:1}]});window.apstag.init(b)}}}
var k={},p={bv:"17.39.1",bfu:"https://live.demand.supply"},z=p.bv;k.c=p.bfu;k.H=z;p.it&&(k.w=!0);var u=["script","link","iframe"],t={g:function(b){this.m(b,{path:"x",u:"ce"})},m:function(b,e){var m=e.path,r=e.u,v=e.N;e=new window.XMLHttpRequest;b=k.c+("/"+m+"/e.js?"+r+"="+b)+((v?"&"+v:"")+("&dsReferer="+btoa(location.href.replace(/^https?:\/\/(www.)?/,"").replace(/\?.*$/,"").substr(0,512)))).substring(0,1E3);e.open("HEAD",b,!0);e.send()}},y={aa:function(){var b=n("/up.js");this.C("ll",b?"d="+b.duration+
"&cs="+b.I:"nd=1")},ea:function(){t.g("rl")},ba:function(){t.g("mle")},ca:function(){t.g("bnl")},da:function(){t.g("nsi")},C:function(b,e){t.m(b,{path:"e",u:"e",N:void 0===e?"":e})}},A={ha:{ga:"ca-pub-3831894559014614"},ja:{D:"44890869"},na:{D:"19820"},fa:{T:"66ef05f7-ad53-48f6-873a-ac7543370392"},P:{U:"253061934"}};p={O:function(){[k.c+"/"+((g()?"impl":"impl-legacy")+".v"+k.H)+".js"].concat(k.w?[]:["https://securepubads.g.doubleclick.net/tag/js/gpt.js"]).forEach(function(m){return a(m,!1)});if(window.demandSupplyMSSI){var b=
document.getElementsByTagName("head")[0],e=document.createElement("script");e.appendChild(document.createTextNode("window.msAdsQueue = window.msAdsQueue || [];"));b.appendChild(e);e=document.createElement("script");e.async=!0;e.src="https://adsdk.microsoft.com/pubcenter/sdk.js?siteId="+window.demandSupplyMSSI+"&publisherId="+A.P.U;e.crossOrigin="anonymous";b.appendChild(e)}setTimeout(function(){demandSupply.surge&&demandSupply.surge.mainLoaded||y.ca()},1E4);d()}};z={R:function(){var b=window.location.href.replace(window.location.protocol+
"//","");a(k.c+"/p4/v17-37-0/"+btoa(b),!1)},S:function(){var b=new XMLHttpRequest;b.open("GET",k.c+"/ds.2.html");b.send()}};var H={X:function(){window.onmessage=function(e){try{if("https://live.demand.supply"===e.origin&&"tr"===e.data.mt){var m=JSON.parse(e.data.res);m&&m.length&&(window.demandSupplyTo=m)}}catch(r){console.error(r)}};var b=document.createElement("iframe");b.style.display="none";b.src="https://live.demand.supply/topics/index.html";b.name="demandSupplyTopicsObserver";document.body.appendChild(b)},
J:function(){try{return"browsingTopics"in document&&document.featurePolicy.allowsFeature("browsing-topics")}catch(b){return!1}}};try{window.demandSupply?y.ea():(window.demandSupply={},y.aa(),p.O(),z.R(),z.S(),H.J()&&H.X())}catch(b){y.ba()}var I;p={bv:"17.39.1",bfu:"https://live.demand.supply"};var O=p.bfu;p.it&&(I=!0);p={fetch:function(){return c({url:O+"/uamp.1.json"}).then(function(b){return JSON.parse(b)}).catch(function(b){console.log("err",b);return{}})}};try{if(!I){var J=l();J.load();J.$()}demandSupply.upmp=
p.fetch()}catch(b){console.error(b)}})();}).call(window)
